all:
	@echo "Los comandos disponibles para el Makefile de la Práctica 1 son los siguientes:"
	@echo "make ayuda_mp"
	@echo "make compila_mp"
	@echo "make ejecuta_mp"
	@echo "make compilar"
	@echo "make ayuda_perceptron"
	@echo "make ejecuta_perceptron"
	@echo "make ayuda_adaline"
	@echo "make ejecuta_adaline"
	@echo "¡IMPORTANTE!, para poder probar la práctica, la carpeta con los ficheros de entrada debe de estar a la altura del makefile"
	@echo "EL fichero impulsos.txt para probar la red de McCulloch-Pitts también debe de estar dentro de esa carpeta!"

ayuda_mp:
	@echo "Para ejecutar el programa realizar la siguiente instrucción"
	@echo "python3 main.py --ejecuta_mp impulsos.txt"
	@echo "Siendo impulsos.txt el nombre del fichero de donde se sacarán los datos"
	@echo "Este fichero debe de estar en la carpeta de bases de datos de la práctica"
	@echo "Esta carpeta, como se comenta con la instruccion make all, debe de estar a la altura del makefile"

compila_mp:
	@echo "Esta instrucción no realiza nada ya que se usa Python"

ejecuta_mp:
	python3 main.py --ejecuta_mp impulsos.txt 

compilar:
	@echo "Esta instrucción no realiza nada ya que se usa Python"

ayuda_perceptron:
	@echo "Para probar el perceptron, realizar la siguiente instrucción"
	@echo "python3 main.py --ejecuta_perceptron problema_real1.txt"
	@echo "Siendo problema_real1.txt el nombre del fichero de donde sacará los datos"
	@echo "Los parametros de la red se pueden cambiar facilmente modificando el fichero: main.py"

ejecuta_perceptron:
	python3 main.py --ejecuta_perceptron problema_real1.txt

ayuda_adaline:
	@echo "Para probar el adaline realizar la siguiente instrucción"
	@echo "python3 main.py --ejecuta_adaline problema_real1.txt"
	@echo "Siendo problema_real1.txt el nombre del fichero de donde sacará los datos"
	@echo "Los parametros de la red se pueden cambiar facilmente modificando el fichero: main.py"

ejecuta_adaline:
	python3 main.py --ejecuta_adaline problema_real1.txt
	










	
